const constants = {
    LOGIN_STATUS:"LOGIN_STATUS",
    ADD_POST:"ADD_POST",
    DELETE_POSTS:"DELETE_POSTS",
    FETCH_POSTS:"FETCH_POSTS",
    FEED_POSTS:"FEED_POSTS",
    EMPTY_LIST:"EMPTY_LIST",
    ERROR:"ERROR",
    LOGGED_OUT:"LOGGED_OUT",
    LOGGED_IN:"LOGGED_IN",
    SET_WEB_URL:"SET_WEB_URL",
    IS_FETCHING:"IS_FETCHING",
    IS_FETCHED:"IS_FETCHED",
    SET_USER_DATA:"SET_USER_DATA"

}

export default constants;