const constants = {
    LOGIN_STATUS:"LOGIN_STATUS",
    ADD_POST:"ADD_POST",
    DELETE_POSTS:"DELETE_POSTS",
    FETCH_POSTS:"FETCH_POSTS",
    FEED_POSTS:"FEED_POSTS",
    EMPTY_LIST:"EMPTY_LIST",
    ERROR:"ERROR"
}

export default constants;